name: my first workflow | shell script

on:
  push:
    branches: main

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:


        - name: Checkout
          uses: actions/checkout@v4

        - name: list files
          run: ls -ltra

        # - name: access
        #   run: chmod +x script1.sh
   
        - name: run shell script
          run: |
            chmod +x script1.sh
             ./script1.sh
